services:
# DATABASE
  db:
    image: postgres:16
    container_name: ${DB_NAME:-ticket-manager-db}
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    shm_size: 128mb
    secrets:
      - db_password
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
# SERVER
  backend:
    build: .
    ports:
      - "${SERVER_PORT:-3000}:${SERVER_PORT:-3000}"
    secrets:
      - db_password
      - jwt_secret
      - encryption_secret
      - blind_index_secret
      - admin_password
    environment:
      SERVER_PORT: ${SERVER_PORT:-3000}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_LASTNAME: ${ADMIN_LASTNAME}
      DB_PASSWORD_FILE: /run/secrets/db_password
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      ENCRYPTION_SECRET_FILE: /run/secrets/encryption_secret
      BLIND_INDEX_SECRET_FILE: /run/secrets/blind_index_secret
      ADMIN_PASSWORD_FILE: /run/secrets/admin_password
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

secrets:
  db_password:
    file: ./secrets/db_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  encryption_secret:
    file: ./secrets/encryption_secret.txt
  admin_password:
    file: ./secrets/admin_password.txt
  blind_index_secret:
    file: ./secrets/blind_index_secret.txt